### ISSUE TITLE
Redirect to the landing page - If user will access a page/url and they are unauthorized/ not logged in

### ISSUE THREAD

**Issue by vbantilan** [dccabs/housecallmd#197]
![image](https://user-images.githubusercontent.com/89785433/135477771-ededd152-7f35-422d-aeb7-718d099bcce1.png)

If someone will access a page that is needed an authorization or user must be logged in- instead of showing blank page- we must redirect it back to the homepage instead

**Comment by lourdesyang1023** [comment]
@vbantilan : about this Dan told me to show a message
 _"You must be logged in and be an admin user to view this page.  Click here to log in. ”_
