### ISSUE TITLE
[UI Issue] - Navbar when Menu Open Z-Index 

### ISSUE THREAD

**Issue by lourdesyang1023** [dccabs/housecallmd#211]
to reproduce: 
- visit `/user-admin` then click any of the menu_(with sub-menu)_ , sub-menu was placed in the bottom stack
<img width="569" alt="image" src="https://user-images.githubusercontent.com/90394642/138461690-7853ed9c-ff3a-4025-a360-ae1274ec7571.png">

**Comment by dccabs** [comment]
closing
