### ISSUE TITLE
Assisted Living Dashboard 

### ISSUE THREAD

**Issue by dccabs** [dccabs/housecallmd#262]
As an admin, I want to be able to go to a dashboard that lists all the centers that have signed up for accounts.  

*Route should be `/facility/admin
*Should look similar to /user-admin
*If not an admin, should get an "Unauthorized" message.
*Should be two tabs, Centers, and Users.
*Centers should show the list of centers in the DB
*For now users can just display a blank section
*Use /api/getFacilities Endpoint

Please check supabase to see fields to display for facilities

**Comment by gr8fuljoe5** [comment]
- [ ] *Route should be `/facility/admin
- [ ] *Should look similar to /user-admin
- [ ] *If not an admin, should get an "Unauthorized" message.
- [ ] *Should be two tabs, Centers, and Users.
- [ ] *Centers should show the list of centers in the DB
- [ ] *For now users can just display a blank section
- [ ] *Use /api/getFacilities Endpoint

**Comment by gr8fuljoe5** [comment]
@dccabs So for the Centers tab, we're just listing the centers? Is there any other data needed?
