### ISSUE TITLE
Assisted Living - Endpoint - Create patient

### ISSUE THREAD

**Issue by dccabs** [dccabs/housecallmd#277]
As a developer I want to create an endpoint that will

1. Add a patient to supabase
2. Add the uuid of the facility they belong to.
3. only a facility can access this endpoint, and must be logged in.
4. the supabase table is called `facility_patients`

**Comment by gr8fuljoe5** [comment]
- [ ] Add a patient to supabase

- [ ] Add the uuid of the facility they belong to.

- [ ] only a facility can access this endpoint, and must be logged in.

- [ ] the supabase table is called facility_patients
