### ISSUE TITLE
Make the UI look nice on my-account page

### ISSUE THREAD

**Issue by dccabs** [dccabs/housecallmd#462]
Please use your best judgement and using MUI to make this page look better.

login with my credentials

dccabs@gmail.com/NYmets45!

/my-account

I think something kind of like this may look nice with the two card layout.

Account info on the left and dependents info on the right

https://tailwindui.com/components/application-ui/page-examples/detail-screens#component-80034b9052ca551c25f7d731b7b3c6dd

If you want to install tailwinds and use that I'd be cool with that.  I'd like to get away from using MUI anyway.

![Screen Shot 2022-09-11 at 6 00 23 PM](https://user-images.githubusercontent.com/558687/189552609-a69fb819-f848-4767-aca1-eed1fc562979.png)

**Comment by lourdesyang1023** [comment]
@dccabs yes we can add tailwindcss on our housecallMD but i think its better if we will create a new task on this and maybe we can migrate it so that the design is consistent. thoughts?
