### ISSUE TITLE
Admin - Appointment tab open modal to user

### ISSUE THREAD

**Issue by dccabs** [dccabs/housecallmd#545]
On this page

https://staging.housecallmd.org/user-admin

login: dccabs@gmail.com/NYmets45!

- Currently if you click on a row it opens up an appointment tab.

- Make the Name column hyperlink the name and open up a modal like it does when you click a row on the users page.
- Clicking elsewhere on the row should do what it does now.
- There is a way to do a custom render for a cell in material table.

<img width="1939" alt="Screen Shot 2022-11-30 at 7 56 04 PM" src="https://user-images.githubusercontent.com/558687/204947360-fa5bd262-c7e9-4634-a3d0-40860d79470f.png">

**Comment by lourdesyang1023** [comment]
Hi @dccabs ,

https://housecallmd-8jl0tukq0-yucaba.vercel.app/user-admin

push updated code for fix on user-admin : https://www.loom.com/share/746a7e5a3f0e4c07aeb73ca1f8005d62
