### ISSUE TITLE
Convert Insurance page design from MUI to Tailwind

### ISSUE THREAD

**Issue by brentbagapuro** [dccabs/housecallmd#551]
https://tailwinds.housecallmd.org/insurance

**Comment by lourdesyang1023** [comment]
design base on this component/s
- https://tailwindui.com/components/marketing/sections/cta-sections#component-25ce2a81d17545994655ccc4062651a4
- https://tailwindui.com/components/marketing/sections/cta-sections#component-1db4588d58587eda7cf40b260dc30833
