### ISSUE TITLE
Improve navigation on admin pages when in mobile view

### ISSUE THREAD

**Issue by brentbagapuro** [dccabs/housecallmd#561]
On pages:

https://staging.housecallmd.org/user-admin
https://staging.housecallmd.org/facility/admin
https://staging.housecallmd.org/facility/admin/user-details/1
https://staging.housecallmd.org/facility/admin/facility-details/f9602bcf-8e99-4aab-96ef-658962ed55f8

Replace Tabs with dropdown menu instead when in mobile view. Make sure the selected option still reflects the tab content they represent.

If possible, create a dropdown using tailwinds.

![image](https://user-images.githubusercontent.com/25628818/210231980-3f32b1a6-88c6-40fb-886c-6e9c315f719b.png)

Note from Dan, I would just use a dropdown select from tailwind ui to reflect the section they are on in mobile.  Could just use this component.

https://tailwindui.com/components/application-ui/forms/select-menus#component-79592f355ca6f6e3b081e0158109981c

Since this is the `simple native` it will invoke the phones select functionality to navigate.

**Comment by dccabs** [comment]
see PR https://github.com/dccabs/housecallmd/pull/585
